name: CI
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
  cypress-run:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NEXT_PUBLIC_FEATURE_ENV: preproduction
          GFW_API_KEY: ${{ secrets.GFW_API_KEY }}
        with:
          start: yarn dev
          wait-on-timeout: 120
          wait-on: 'http://localhost:3000'
